In [21]:
import numpy as np
def fixed_point_iteration(g, x0, tol=1e-6, max_iter=1000):
    approximations = np.zeros(max_iter + 1)  # Initialize a NumPy array to store approximations
    approximations[0] = x0  # Set the initial value
    
    x = x0
    for iter_count in range(1, max_iter + 1):
        x_next = g(x)
        approximations[iter_count] = x_next  # Store the approximation
        
        # Check if the difference between successive iterations is within tolerance
        if abs(x_next - x) < tol:
            return approximations[:iter_count + 1]  # Return the array up to the last computed value
        
        x = x_next
    
    return approximations  # Return the full array if it didn't converge

In [22]:
def g1(x):
    return (10/(x+4))**0.5

g1_arr = fixed_point_iteration(g1,1.5 , tol=1e-10)

In [23]:
def order(x,xstar):
    diff1 = np.abs(x[1::]-xstar)
    diff2 = np.abs(x[0:-1]-xstar)
    fit = np.polyfit(np.log(diff2.flatten()),np.log(diff1.flatten()),1)
    alambda = np.exp(fit[1])
    alpha = fit[0]
    print(f'lambda is {alambda}')
    print(f'alpha is {alpha}')
    return fit

In [24]:
order(g1_arr, 1.3652300134140976)

lambda is 0.1265274282031372
alpha is 0.9996909905165663


array([ 0.99969099, -2.06729617])

In [33]:
def aitken_delta_squared(sequence_func, x0, tol=1e-6, max_iter=1000):
   
    approximations = np.zeros(max_iter + 1)  # Store original approximations
    accelerated_approximations = np.zeros(max_iter + 1)  # Store accelerated approximations
    
    approximations[0] = x0
    accelerated_approximations[0] = x0
    
    for iter_count in range(1, max_iter - 2):  # Aitken's method requires at least 3 consecutive points
        
        # Generate the next sequence points
        p_n = approximations[iter_count - 1]
        p_np1 = sequence_func(p_n)  # p_(n+1)
        p_np2 = sequence_func(p_np1)  # p_(n+2)
        
        approximations[iter_count] = p_np1
        
        # Aitken's ∆² acceleration formula
        denominator = p_np2 - 2 * p_np1 + p_n
        if abs(denominator) < 1e-12:  # Avoid division by a very small number
            return accelerated_approximations[:iter_count]  # Return the current sequence
        
        accelerated_approx = p_n - (p_np1 - p_n) ** 2 / denominator
        accelerated_approximations[iter_count] = accelerated_approx
        
        # Check for convergence
        if abs(accelerated_approx - p_n) < tol:
            return accelerated_approximations[:iter_count + 1]
        
        # Update the next guess
        approximations[iter_count + 1] = p_np2
    
    return accelerated_approximations



In [34]:
# Applying the Aitken's ∆² method
accelerated_approximations = aitken_delta_squared(g1, 1.5, tol=1e-10, max_iter=100)

# Output the accelerated approximations
print(accelerated_approximations)

[1.5        1.36526522 1.36523058 1.36523002 1.36523001 1.36523001
 1.36523001 1.36523001 1.36523001 1.36523001 1.36523001 1.36523001
 1.36523001]


In [47]:
import numpy as np

def steffenson_method(g, p0, tol=1e-6, max_iter=1000):

    approximations = np.zeros(max_iter + 1)  # To store all approximations
    approximations[0] = p0  # Start with the initial guess
    
    pn = p0  # Start with the initial guess
    
    for iter_count in range(1, max_iter + 1):
        a = pn  # Current approximation
        b = g(a)  # Apply g once
        c = g(b)  # Apply g again
        
        # Calculate the next approximation using Aitken's ∆² formula
        denominator = c - 2 * b + a
        
        # Avoid division by a very small number (or zero)
        if abs(denominator) < 1e-12:
            print(f"Warning: Small denominator at iteration {iter_count}")
            return approximations[:iter_count]  # Return the current sequence
        
        pn_next = a - (b - a)**2 / denominator  # Update the next approximation
        
        approximations[iter_count] = pn_next  # Store the new approximation
        
        # Check for convergence
        if abs(pn_next - pn) < tol:
            return approximations[:iter_count + 1]  # Return the sequence up to convergence
        
        # Update pn to pn_next for the next iteration
        pn = pn_next
    
    return approximations  




In [50]:


# Initial guess
p0 = 1.5

# Run Steffenson's method
new = steffenson_method(g1, p0, tol=1e-10, max_iter=100)
new


array([1.5       , 1.36526522, 1.36523001, 1.36523001])

In [51]:
order(new,1.3652300134140976)

lambda is 6.675197214498497e-06
alpha is 0.9278955281457948


array([  0.92789553, -11.91711181])